name: iridium_reader_widget
description: Plug and play ebook reader widget
version: 0.0.1
homepage: https://dart.dev/tools/pub/pubspec

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  mno_commons:
    path: packages/mno_commons
  mno_navigator:
    path: packages/mno_navigator_flutter
  mno_opds:
    path: packages/mno_opds
  mno_server:
    path: packages/mno_server
  mno_shared:
    path: packages/mno_shared
  mno_streamer:
    path: packages/mno_streamer

dev_dependencies:
  flutter_lints: ^4.0.0
  melos: ^3.4.0