name: iridium_monorepo
description: Plug and play ebook reader widget
version: 0.0.1
homepage: https://dart.dev/tools/pub/pubspec

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dependency_overrides:
  platform: ^3.1.0

dev_dependencies:
  flutter_lints: ^4.0.0
  melos: ^3.4.0