name: iridium_reader_widget
description: Plug and play ebook reader widget
version: 0.0.1
homepage: https://dart.dev/tools/pub/pubspec

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  mno_commons: ^0.1.0
  mno_server: ^0.1.0
  mno_streamer: ^0.1.0
  mno_opds: ^0.1.0
  mno_shared: ^0.1.0
  mno_navigator: ^0.1.0

#     path: mno_shared_dart
#   cupertino_icons: ^1.0.4
#   provider: ^6.0.2
#   shared_preferences: ^2.0.12
#   #  flutter_icons: ^1.1.0
#   flutter_font_icons: ^2.2.4
#   xml2json: ^5.3.2
#   fluttertoast: ^8.0.8
# #  cached_network_image: ^3.2.0
#   uuid: ^3.0.5
#   objectdb: ^1.2.1+1
#   path_provider: ^2.0.8
#   dio: ^4.0.4
#   permission_handler: ^8.3.0
#   google_fonts: ^2.2.0
# #  flutter_spinkit: ^5.1.0
#   idb_shim: ^2.0.1
# #  idb_sqflite: ^1.1.0
# #  sqflite_common_ffi: ^2.1.0+2
#   flutter_fimber: ^0.6.4
#   bloc: ^8.0.2
#   flutter_bloc: ^8.0.1
#   flutter_inappwebview: ^5.3.2
#   json_theme: ^3.2.5
#   new_version: ^0.3.0

  dartx: any
  fimber: any
  flutter_inappwebview: any
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/

  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
