name: mno_shared
description: Contains the definitions of the custom types (model) used across the Readium-2 Dart projects.
version: 0.1.3
homepage: https://github.com/Mantano/mno_shared_dart
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  http: ^1.2.1
  image: ^3.3.0
  intl: ^0.17.0
  mno_commons: ^0.1.0
  xml: ^6.5.0
dev_dependencies:
  image_compare: ^1.1.2
  lints: ^1.0.1
  test: ^1.20.1
