name: mno_opds
description: Contains OPDS1 and OPDS2 parsers using OPDS classes provided by mno_shared.
version: 0.1.1
homepage: https://github.com/Mantano/mno_opds_dart
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  mno_commons: ^0.1.0
  mno_shared: ^0.1.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
