name: mno_server
description: Contains the server functions to serve resources in the webview.
version: 0.1.0
homepage: https://github.com/Mantano/mno_server_dart
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.0.2
  rxdart: ^0.27.3
  mno_commons: ^0.1.0
  mno_shared: ^0.1.0
dev_dependencies:
  lints: ^1.0.1
